### PR TITLE
i18n pt_BR

### PR DESCRIPTION
**Pull request by FJBelmonte**
added missing entries on pt_BR, based on es_ES

### CODE REVIEW

**Comment by vjrj** [comment]
Ola @FJBelmonte . These kind of PR are not needed now because on each new crowdin translation an ala-i18n deb package is published with them. So we don't have to wait to ALA releases including new translations.

See:
https://github.com/living-atlases/ala-i18n
https://github.com/living-atlases/ala-i18n#install

So I close it and install ala-i18n debian package that should include this and other translations (BR, Spanish, ... ).

Thanks!

**Comment by FJBelmonte** [comment]
hola @vjrj 

I think I'm confused about the crowdin interface (or access hierarchy), I didn't see an option to add some id in the pt_BR file.

the pt_BR file and interface of the userdetails module in crowdin has 56 entries. And it has 100% of the translation (not yet verified)

while the original message.properties has 212 entries.

I used an adaptation of the ala-i18n deb package, for my scenario. And that's when I identified that one of the modules did not translate into Portuguese,
only translated into Spanish.

Can you help me how to proceed?

/userdetails/registration/createAccount?lang=pt_BR messages_pt_BR.properties from  ala-i18n deb package
Screen Shot 2021-12-17 at 19 48 13

status from userdetails pt_BR in crowdin 
Screen Shot 2021-12-17 at 19 48 29

/userdetails/registration/createAccount?lang=pt_BR with custom messages_pt_BR.properties from  this PR
Screen Shot 2021-12-17 at 19 50 15

Screen Shot 2021-12-17 at 19 57 31

thankful

**Comment by vjrj** [comment]
Ola, @FJBelmonte first of all, can we invite you to our slack channel? Using fe...@live.com?

Things about our crowdin use:
- We auto-sync stable branchs (not the development branchs). So on new releases, we can start to translate
- the verification of crowdin is something that we are not using. We are packaging all the translations, verified or not.
- in the case of userdetails the crowdin integration was not merged in master so we were using a workaround and I forget to remove it. Now should be updated.

The i18n deb build is failing since the past week for some reason. I'm trying to fix it.

**Comment by FJBelmonte** [comment]
> Ola, @FJBelmonte first of all, can we invite you to our slack channel? Using [fe...@live.com](mailto:fe...@live.com)?
Sure

> Things about our crowdin use:
> 
> * We auto-sync stable branchs (not the development branchs). So on new releases, we can start to translate
Good to know
> * the verification of crowdin is something that we are not using. We are packaging all the translations, verified or not.
already knew, but is it possible to fix existing errors?
> * in the case of userdetails the crowdin integration was not merged in master so we were using a workaround and I forget to remove it. Now should be updated.
the missing entries?
> 
> The i18n deb build is failing since the past week for some reason. I'm trying to fix it.

**Pull request closed without merging**
